language: php

php:
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --dev --prefer-dist -o
  - composer require codacy/coverage --dev
  # - composer require codeception/codeception --dev

script:
  - ./vendor/bin/phpunit --coverage-clover build/coverage/xml
  # - ./vendor/bin/codecept run unit --coverage --coverage-xml

after_script: 
  - php vendor/bin/codacycoverage clover build/coverage/xml
  # - php vendor/bin/codecept clover
